#!/bin/bash

# Loads all defined colors
source "$CONFIG_DIR/colors.sh"

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# ======================
# BAR (Hyprland-like)
# ======================

sketchybar --bar \
  height=34 \
  margin=12 \
  y_offset=8 \
  blur_radius=30 \
  color=$TN_BASE \
  border_width=0 \
  corner_radius=16 \
  padding_left=5 \
  padding_right=5

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:SemiBold:12.0" \
  icon.color=$ITEM_COLOR \
  label.font="JetBrainsMonoNL Nerd Font:SemiBold:12.0" \
  label.color=$ITEM_COLOR \
  background.color=$ACCENT_COLOR \
  background.corner_radius=9 \
  background.height=18 \
  padding_left=5 \
  padding_right=5 \
  icon.padding_left=8 \
  icon.padding_right=3 \
  label.padding_left=3 \
  label.padding_right=10

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
# source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh
# source $ITEM_DIR/cpu.sh
# source $ITEM_DIR/memory.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
